version: '3'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
  backend:
    build: .
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - "18080:18080"